version: '3'
services:
  echo:
    build: ./echo
    volumes:
      - ./echo:/go/src/echo
    ports:
      - 0.0.0.0:10007:10007
    tty: true
  telnet:
    build: ./telnet
    volumes:
      - ./telnet:/go/src/telnet
    ports:
      - 0.0.0.0:10023:10023
    tty: true
